// frontend/src/components/AboutCard.vue
<template>
  <q-card class="col-12" flat>
    <q-card-section class="q-pa-none">
      <div
        class="row items-center q-pa-md text-white"
        :class="`bg-${info.theme}`"
      >
        <q-avatar size="80px" class="q-mr-md">
          <q-icon :name="info.icon" size="40px" />
        </q-avatar>
        <div>
          <div class="text-h4 text-weight-bold">{{ info.name }}</div>
          <div class="text-h6">{{ info.role }}</div>
        </div>
      </div>
    </q-card-section>

    <q-card-section class="q-pt-xl">
      <div class="row q-col-gutter-lg">
        <div class="col-12 col-md-6">
          <div class="text-h6 q-mb-md" :class="`text-${info.theme}`">
            {{ info.expertise.label }}
          </div>
          <q-list bordered class="rounded-borders" separator>
            <q-item
              v-for="(item, idx) of info.expertise.items"
              :key="`expertise-${idx}`"
            >
              <q-item-section avatar>
                <q-icon :name="item.icon" :color="info.theme" />
              </q-item-section>
              <q-item-section>
                <q-item-label class="text-weight-medium">{{
                  item.title
                }}</q-item-label>
                <q-item-label caption>{{ item.subtitle }}</q-item-label>
              </q-item-section>
            </q-item>
          </q-list>
        </div>

        <div class="col-12 col-md-6" v-if="info.career">
          <div class="text-h6 q-mb-md" :class="`text-${info.theme}`">
            {{ info.career.label }}
          </div>

          <div class="q-pl-md">
            <template
              v-for="(item, idx) of info.career.items"
              :key="`career-${idx}`"
            >
              <div class="q-mb-lg">
                <div class="text-weight-bold text-body1">{{ item.year }}</div>
                <div class="text-caption">{{ item.caption }}</div>
              </div>
            </template>
          </div>
        </div>
      </div>
    </q-card-section>
  </q-card>
</template>

<script setup>
const props = defineProps(["info"]);
</script>

// react-frontend/src/components/AboutCard.tsx
// components/AboutCard.tsx
import { useMediaQuery } from 'react-responsive';
import type { AboutInfo } from '../types/about';
import Icon from './Icon'

interface AboutCardProps {
    info: AboutInfo;
}

const AboutCard = ({ info }: AboutCardProps) => {
    const isMediumOrLarger = useMediaQuery({ minWidth: 768 });

    const getThemeColor = (type: 'bg' | 'text') => {
        return `${type}-[${info.theme}]`;
    };

    return (
        <div className="w-full bg-white rounded-lg shadow-sm">
            <div className="p-0">
                <div
                    className={`flex items-center p-4 text-white ${getThemeColor('bg')}`} style={{ backgroundColor: info.theme }}
                >
                    {isMediumOrLarger && (
                        <div className="w-20 h-20 mr-4 flex items-center justify-center rounded-full bg-white/20">
                            {/* Use Icon component for the main avatar icon */}
                            <Icon name={info.icon} size={40} className="text-4xl" />
                        </div>
                    )}
                    <div>
                        <div className="text-3xl font-bold">{info.name}</div>
                        <div className="text-xl">{info.role}</div>
                    </div>

                </div>
            </div>

            <div className="pt-12 px-6">
                <div className="flex flex-wrap -mx-4">
                    <div className="w-full md:w-6/12 px-4 mb-6">
                        <div className={`text-xl font-semibold mb-4`} style={{ color: info.theme }}>
                            {info.expertise.label}
                        </div>
                        <div className="border rounded-lg divide-y">
                            {info.expertise.items.map((item, idx) => (
                                <div
                                    key={`expertise-${idx}`}
                                    className="flex items-center p-4"
                                >
                                    <div className="w-12 h-12 flex items-center justify-center mr-4">
                                        {/* Use Icon component for expertise items */}
                                        <Icon
                                            name={item.icon}
                                            size={24}
                                            style={{ color: info.theme }}
                                        />
                                    </div>
                                    <div className="flex-1">
                                        <div className="font-medium">{item.title}</div>
                                        <div className="text-sm text-gray-500">{item.subtitle}</div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>

                    {info.career && (
                        <div className="w-full md:w-6/12 px-4 mb-6">
                            <div className={`text-xl font-semibold mb-4`} style={{ color: info.theme }}>
                                {info.career.label}
                            </div>

                            <div className="pl-4">
                                {info.career.items.map((item, idx) => (
                                    <div key={`career-${idx}`} className="mb-6">
                                        <div className="font-bold text-base">{String(item.year)}</div>
                                        <div className="text-sm text-gray-600">{item.caption}</div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};

export default AboutCard;
